// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROJECT.Models;

public partial class Address
{
    public int StudentId { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public virtual Student Student { get; set; }
}