// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROJECT.Models;

public partial class Assignment
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int CourseId { get; set; }

    public virtual Course Course { get; set; }
}