// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PROJECT.Models;

public partial class Course
{
    public int Id { get; set; }

    public string CourseName { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}